### ISSUE TITLE
admin 기능을 구현해야함

### ISSUE THREAD

**Issue by tomatozil** [tomatozil/purchase_project#11]
#### what features?
test를 하려니까 필요하다 ?!
⭐️new는 해놓고 추가한 것들

#### to-do list
- [x] UserEntity에 RoleType 프로퍼티 추가 ⭐️new
- [x] slot 추가 api (stock 데이터도 자동 추가)
- [x] user의 role을 변경하는 api ⭐️new
- [x] user의 role을 검사하는 interceptor ⭐️new
- [x] test ⭐️new

#### 뻘짓하면서 배운점
1. 서버가 다시 올라가면 토큰이 무효화됨
    1. 바보야 secret key가 서버가 올라갈 때마다 새로 만들어지잖아.
    2. 하나 정해놓고 계속 쓰게 만들어야지 그럴때는 뭐다? .env 파일이다.

1. app과 DB 연결시 url 이 중요하다(당연하지만)
    1. java application 컨테이너와  mysql 컨테이너 연결시, 그냥 local 의 java application 과 mysql 컨테이너 연결시 Dockerfile의 EXPOSE나 docker compose.yml 파일의 port 부분을 잘 활용해야함.
    2. local port:container port

1. Json to Object / Object to Json 직렬화 역직렬화시 중요한 것은 프로퍼티 이름이다
    1. 웬만하면 일치하는게 좋음^ ^ 
    2. 일치해도 문제다? 그러면 아래와 같은 이유임.
        1. 기본적으로 Jackson은 매개변수가 있는 생성자에 대해 자동으로 매핑을 시도하지 않으며, 기**본 생성자와 setter 메서드를 통해 역직렬화를 수행**합니다. 하지만 생성자를 통해 객체를 생성할 경우, 매개변수와 JSON 필드를 연결하는 명확한 방법이 필요합니다.

#### references
[java interceptor](https://kylo8.tistory.com/entry/Spring-boot-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-JWT-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%9D%B8%EC%A6%9D%EA%B3%BC-%EA%B6%8C%ED%95%9C-%EA%B4%80%EB%A6%AC-HandlerInterceptor-%EC%9D%B8%EC%A6%9D-%EB%A1%9C%EC%A7%81-%EA%B5%AC%ED%98%84)
