### ISSUE TITLE
재고 조회 방법 개선

### ISSUE THREAD

**Issue by tomatozil** [tomatozil/purchase_project#7]
#### what features?
실험 결과를 바탕으로 재고를 조회하는 방법을 바꿔봅니다.
기존: 재고 조회 요청마다 주문량 count 하기 -> 총 수량 가져오기 -> total - 주문량 연산
개선: 재고 조회 요청시 캐싱해놓은 재고량 읽기

재고량을 (DB에) 저장해놓냐 vs 마냐 였는데 저장하는 방향으로 개선하고자 합니다.
근데 이제 예약할 때, 취소할 때마다 재고량 update가 잘 되어야하는..
동시성 이슈를 잘 처리하는게 중요합니다.

#### to-do list
- [X] Stock Entity 수정 (+ 현재 예약 수 프로퍼티 추가)
- [X] 예약하기 api 수정
- [ ] ~~취소하기 api 추가~~
